<?php echo $this->partial('wizard/header', array('wizard' => $this->wizard)) ?>
<?php
$wizardForm = $this->wizard->getForm();
$wizardForm->setAttribute('id', 'wizard-form');
$wizardForm->prepare();

$currentStep = $this->wizard->getCurrentStep();
?>
<div class="row">
	<div class="col-md-6">
			<?php echo count($wizardForm);  ?>
			<?php /* echo $this->form()->openTag($wizardForm) . PHP_EOL; ?>
				<div class="row">
			    	<?php
				    echo $this->partial($currentStep->getViewTemplate(), array(
				        'form' => $wizardForm->get('step')
				    ));
				    ?>
				</div>
			    <?php echo $this->partial('wizard/buttons', array('wizard' => $this->wizard)) ?>
			<?php echo $this->form()->closeTag($wizardForm) . PHP_EOL; */ ?>
	</div>
</div>